name: 'Duanzd Switch Test'
packageKey: 'duanzd-switch-test'
permissions:
  zigbee: {}
description: "SmartThings driver for Zigbee switch devices"
vendorSupportInformation: "https://support.smartthings.com"
